### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by jpotts** [OrderOfTheBee/alfresco-pdf-toolkit#28]
I can no longer build the project after pulling the latest from head.

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.alfresco.extension:repo:[unknown-version]: Failure to find org.alfresco.extension:pdf-toolkit:pom:1.4.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 21, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.alfresco.extension:repo:[unknown-version](/opt/src/alfresco-pdf-toolkit/repo/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.alfresco.extension:repo:[unknown-version]: Failure to find org.alfresco.extension:pdf-toolkit:pom:1.4.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 21, column 13 -> [Help 2]

**Comment by sujaypillai** [comment]
I just updated the parent version for [https://github.com/ntmcminn/alfresco-pdf-toolkit/blob/master/repo/pom.xml](url) from 1.4.0 to 1.4.1 and the build works fine.

**Comment by douglascrp** [comment]
This is not an issue anymore.
Closing it.
