### ISSUE TITLE
No input field if watermark type is text - Watermark issue

### ISSUE THREAD

**Issue by sumitt** [OrderOfTheBee/alfresco-pdf-toolkit#32]
Hi,

How can we give a value if there is need to watermark with text? Because it looks that there is no such filed to input text value and operation gets failed. PFA screenshots.

Thanks
Sumit
![watermark-issue](https://cloud.githubusercontent.com/assets/3921345/20553239/e85b0bd0-b178-11e6-8c42-e27e324fb6b8.png)

**Comment by douglascrp** [comment]
The text field is available in the current version.
Please, try again.

I am closing this one.
