### ISSUE TITLE
PDF Toolkit watermarking

### ISSUE THREAD

**Issue by zoko123** [OrderOfTheBee/alfresco-pdf-toolkit#45]
PDF toolkit watermarking ignores request for watermark on specific e.g. first page. It always watermarks all pages. 

I think sorting this out wuold be a great enhancmet of PDF Toolkit.

Would be very gratefull if someone with needed knowledge would deal with it.

Thanks,

ZoKo

![image](https://user-images.githubusercontent.com/32892833/31704047-d4a1c84e-b3df-11e7-8c55-aa68ddae825e.png)

**Comment by douglascrp** [comment]
This is working with the current version.
Please, try again.

Closing it.
