### ISSUE TITLE
can I use this for PDF editing on alfresco 

### ISSUE THREAD

**Issue by kranthi23** [OrderOfTheBee/alfresco-pdf-toolkit#47]
can I use this for PDF editing on alfresco???

**Comment by douglascrp** [comment]
It all depends on what kind of editing features you are looking for.
What the addon allows you to do is to split, merge, sign, etc
But if what you need is to actually change the PDF's content, like text or images, then no, this is not intended to solve your problem.

Please, give us more details on your use case.

**Comment by kranthi23** [comment]
One of use case is about editing actual content of pdf document(like adding more lines or removing some lines or correcting data inside pdf) in alfresco.

Second one is about like adding sticky notes,underlining,highlighting data,adding images in pdf.

**Comment by douglascrp** [comment]
As I imagine, this addon is not what you are searching for.

**Comment by kranthi23** [comment]
Douglascrp thanks for your responses.Can you give me any ideas to do document annotations and audit trails in alfresco.

**Comment by douglascrp** [comment]
@kranthi23 Please, use http://community.alfresco.com/ to find more information on the topic.
There you will find more people willing to help.

I am closing this one now.
